//front/src/context/indiceCamps.js
export const INDICE_CAMPS = [
  { id_camp: "370", IdCamp: "370", nombre: "370_Leads Externo OncoSalud", Campana: "370_Leads Externo OncoSalud", campana: "370_Leads Externo OncoSalud" },
  { id_camp: "340", IdCamp: "340", nombre: "340_Ricardo Palma", Campana: "340_Ricardo Palma", campana: "340_Ricardo Palma" },
  { id_camp: "760", IdCamp: "760", nombre: "Zaaz", Campana: "Zaaz", campana: "Zaaz" },
  { id_camp: "90", IdCamp: "90", nombre: "90_Interseguro Vida", Campana: "90_Interseguro Vida", campana: "90_Interseguro Vida" },
  { id_camp: "10", IdCamp: "10", nombre: "Interseguro Soat", Campana: "Interseguro Soat", campana: "Interseguro Soat" },
  { id_camp: "20", IdCamp: "20", nombre: "Caja Arequipa", Campana: "Caja Arequipa", campana: "Caja Arequipa" },
  { id_camp: "21", IdCamp: "21", nombre: "CAJA AREQUIPA BACK", Campana: "CAJA AREQUIPA BACK", campana: "CAJA AREQUIPA BACK" },
  { id_camp: "30", IdCamp: "30", nombre: "30_OncoSalud", Campana: "30_OncoSalud", campana: "30_OncoSalud" },
  { id_camp: "70", IdCamp: "70", nombre: "AunaSalud", Campana: "AunaSalud", campana: "AunaSalud" },
  { id_camp: "75", IdCamp: "75", nombre: "AUNA VIDA", Campana: "AUNA VIDA", campana: "AUNA VIDA" },
  { id_camp: "80", IdCamp: "80", nombre: "Interseguro Vehicular", Campana: "Interseguro Vehicular", campana: "Interseguro Vehicular" },
  { id_camp: "160", IdCamp: "160", nombre: "DIRECTV", Campana: "DIRECTV", campana: "DIRECTV" },
  { id_camp: "240", IdCamp: "240", nombre: "Win", Campana: "Win", campana: "Win" },
  { id_camp: "300", IdCamp: "300", nombre: "Atlas Copco", Campana: "Atlas Copco", campana: "Atlas Copco" },
  { id_camp: "350", IdCamp: "350", nombre: "Auna Digital", Campana: "Auna Digital", campana: "Auna Digital" },
  { id_camp: "220", IdCamp: "220", nombre: "Biznes Digital Win", Campana: "Biznes Digital Win", campana: "Biznes Digital Win" },
  { id_camp: "700", IdCamp: "700", nombre: "TLKM", Campana: "TLKM", campana: "TLKM" },
  { id_camp: "710", IdCamp: "710", nombre: "auto", Campana: "auto", campana: "auto" },
  { id_camp: "720", IdCamp: "720", nombre: "Autorizacion Campo", Campana: "Autorizacion Campo", campana: "Autorizacion Campo" },
  { id_camp: "210", IdCamp: "210", nombre: "Bz Digital AunaSalud", Campana: "Bz Digital AunaSalud", campana: "Bz Digital AunaSalud" },
  { id_camp: "230", IdCamp: "230", nombre: "Bz Digital Win Empresas", Campana: "Bz Digital Win Empresas", campana: "Bz Digital Win Empresas" },
  { id_camp: "250", IdCamp: "250", nombre: "PRUEBA", Campana: "PRUEBA", campana: "PRUEBA" },
  { id_camp: "260", IdCamp: "260", nombre: "Bz Digital Win Provincias", Campana: "Bz Digital Win Provincias", campana: "Bz Digital Win Provincias" },
  { id_camp: "420", IdCamp: "420", nombre: "Bzg Campo Win", Campana: "Bzg Campo Win", campana: "Bzg Campo Win" },
  { id_camp: "280", IdCamp: "280", nombre: "Nubyx", Campana: "Nubyx", campana: "Nubyx" },
  { id_camp: "270", IdCamp: "270", nombre: "Claro", Campana: "Claro", campana: "Claro" },
  { id_camp: "290", IdCamp: "290", nombre: "Bz Digital OncoSalud Fria", Campana: "Bz Digital OncoSalud Fria", campana: "Bz Digital OncoSalud Fria" },
  { id_camp: "330", IdCamp: "330", nombre: "Verisure", Campana: "Verisure", campana: "Verisure" },
  { id_camp: "360", IdCamp: "360", nombre: "Bz Digital Verisure", Campana: "Bz Digital Verisure", campana: "Bz Digital Verisure" },
  { id_camp: "380", IdCamp: "380", nombre: "Movistar", Campana: "Movistar", campana: "Movistar" },
  { id_camp: "60", IdCamp: "60", nombre: "60_Interseguro Rumbo", Campana: "60_Interseguro Rumbo", campana: "60_Interseguro Rumbo" },
  { id_camp: "310", IdCamp: "310", nombre: "310_Bz Digital PeruFibra", Campana: "310_Bz Digital PeruFibra", campana: "310_Bz Digital PeruFibra" },
  { id_camp: "50", IdCamp: "50", nombre: "Ojt Nexum", Campana: "Ojt Nexum", campana: "Ojt Nexum" },
  { id_camp: "702", IdCamp: "702", nombre: "TLKM_ADMIN", Campana: "TLKM_ADMIN", campana: "TLKM_ADMIN" },
  { id_camp: "460", IdCamp: "460", nombre: "460 Leads Sorteo OncoSalud", Campana: "460 Leads Sorteo OncoSalud", campana: "460 Leads Sorteo OncoSalud" },
  { id_camp: "40", IdCamp: "40", nombre: "40 CROSS AUNA", Campana: "40 CROSS AUNA", campana: "40 CROSS AUNA" },
  { id_camp: "730", IdCamp: "730", nombre: "730 Distribuidor Promotor", Campana: "730 Distribuidor Promotor", campana: "730 Distribuidor Promotor" },
  { id_camp: "200", IdCamp: "200", nombre: "200_Bz Digital OncoSalud", Campana: "200_Bz Digital OncoSalud", campana: "200_Bz Digital OncoSalud" }
];